Update abh

diff --git a/abh b/abh
--- a/abh
+++ b/abh
@@ -1,3 +1,6 @@
+# License: https://github.com/sakibulalikhan/asus-battery-health/blob/main/LICENSE
+# GitHub: https://github.com/sakibulalikhan/asus-battery-health
+
 #!/bin/bash
 
 # Print script header
@@ -30,11 +33,25 @@ if [ $# -eq 0 ]; then
   display_help
 fi
 
+# Function for logging
+log_message() {
+  TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
+  echo "$TIMESTAMP $1"
+}
+
 # Parse command-line arguments
 while getopts ":t:rvh" opt; do
   case ${opt} in
     t )
-      CHARGE_THRESHOLD=$OPTARG
+      case $OPTARG in
+        60|80|100)
+          CHARGE_THRESHOLD=$OPTARG
+          ;;
+        *)
+          log_message "Error: Charge threshold must be 60, 80, or 100. (Recomended by Asus Battery Healh!)" >&2
+          exit 1
+          ;;
+      esac
       ;;
     r )
       REMOVE_THRESHOLD=true
@@ -54,24 +71,42 @@ done
 
 # Determine the battery name
 BATTERY_NAME=$(ls /sys/class/power_supply | grep "BAT")
+if [ -z "$BATTERY_NAME" ]; then
+  log_message "Error: Battery name not found. Exiting."
+  exit 1
+fi
 
 # Function to display verbose messages
 verbose() {
   if [ "$VERBOSE_MODE" = true ]; then
-    echo "$1"
+    log_message "$1"
+    if [ "$1" == "Systemd service status:" ]; then
+      echo
+      sudo systemctl status asus-battery-health.service --no-pager
+    fi
   fi
 }
 
 if [ -n "$REMOVE_THRESHOLD" ]; then
   # Remove the charge threshold
   verbose "Removing the charge threshold..."
-  echo 100 | sudo tee /sys/class/power_supply/$BATTERY_NAME/charge_control_end_threshold > /dev/null
+  if echo 100 | sudo tee /sys/class/power_supply/$BATTERY_NAME/charge_control_end_threshold > /dev/null; then
+    verbose "Charge threshold removed successfully."
+  else
+    log_message "Error: Failed to remove the charge threshold."
+    exit 1
+  fi
 
   # Remove the systemd service
   verbose "Disabling systemd service..."
-  sudo systemctl disable asus-battery-health.service > /dev/null
-  sudo systemctl stop asus-battery-health.service > /dev/null
-  sudo rm /etc/systemd/system/asus-battery-health.service > /dev/null
+  if sudo systemctl disable asus-battery-health.service > /dev/null && \
+     sudo systemctl stop asus-battery-health.service > /dev/null && \
+     sudo rm /etc/systemd/system/asus-battery-health.service > /dev/null; then
+    verbose "Systemd service disabled successfully."
+  else
+    log_message "Error: Failed to disable the systemd service."
+    exit 1
+  fi
 
   echo "Asus Battery Health Charging has been disabled."
 else
@@ -89,7 +124,7 @@ Wants=network-online.target
 
 [Service]
 Type=simple
-ExecStart=/bin/bash -c "while true; do echo $CHARGE_THRESHOLD > /sys/class/power_supply/$BATTERY_NAME/charge_control_end_threshold; sleep 60; done"
+ExecStart=/bin/bash -c "echo $CHARGE_THRESHOLD > /sys/class/power_supply/$BATTERY_NAME/charge_control_end_threshold"
 
 [Install]
 WantedBy=multi-user.target
@@ -99,7 +134,6 @@ EOF
   sudo systemctl enable asus-battery-health.service > /dev/null
   sudo systemctl start asus-battery-health.service > /dev/null
 
-  echo "Asus Battery Health Charging has been enabled with a charge threshold of $CHARGE_THRESHOLD%."
+  log_message "Asus Battery Health Charging has been enabled with a charge threshold of $CHARGE_THRESHOLD%."
   verbose "Systemd service status:"
-  sudo systemctl status asus-battery-health.service | sed -n '/^●/p'
 fi
